module.exports = {
  // * Error Responses
  SERVER_ERROR: 'SERVER_ERROR_REQUEST_REJECTED',
  UNAUTHORIZED_REQUEST: 'UNAUTHORIZED_REQUEST_REJECTED',
  INVALID_REQUEST: 'INVALID_REQUEST_REJECTED',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND_REQUEST_REJECTED',
  ENTITY_ALREADY_EXISTS: 'ENTITY_ALREADY_EXISTS',
  ORDER_FAILED: 'ORDER_REJECTED',
  REQUEST_REJECTED: 'PARAMETER_NEEDED_REQUEST_REJECTED',
  WRONG_CREDENTIALS: 'WRONG_CREDENTIALS',

  // * Success Responses
  REQUEST_SUCCESSFUL: 'REQUEST_SUCCESSFULLY_APPROVED',
  REQUEST_SUCCESSFULLY_SENT: 'REQUEST_SUCCESSFULLY_SENT',
  ORDER_SUCCESSFUL: 'ORDER_SUCCESSFULLY_APPROVED',
  ENTITY_CREATED: 'ENTITY_CREATED_SUCCESSFULLY',
  ENTITY_UPDATED: 'ENTITY_UPDATED_SUCCESSFULLY',
  
  // * Pending Messages
  ORDER_PENDING: 'ORDER_PENDING',
  
}