version: "3.8"
services:
    3s_backend:
      build: 
        context: .
        dockerfile: ./Dockerfile
      stop_signal: SIGINT
      container_name: 3s_api_service
      image: 3s_backend
      ports:
        - "3030:3030"
      # ? For automatically updating the container (for development only)
      volumes:
        - .:/app
      restart: always

    3s_database:
      image: mongo
      container_name: 3s_db_service
      ports:
        - "27017:27017"
      volumes:
        - /data/db:/data/db
      expose:
        - "27017"
      restart: unless-stopped

    3s_minio:
      image: minio/minio
      container_name: 3s_minio_service
      environment:
        - MINIO_ROOT_USER=threesadmin
        - MINIO_ROOT_PASSWORD=C#mpl3x!ty
      command: server /data --console-address ":9001" --address ":443"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
      ports:
        - "9000:9000"
        # - "9001:9001"
      volumes:
        - /tmp/minio/data:/data
        # - /tmp/.minio:/root/.minio
      restart: unless-stopped